oneserver:
  advertiseIp: 0.0.0.0
  port: 10080

cool-app:
  ribbon:
    listOfServers: 127.0.0.1:10080
    NFLoadBalancerPingInterval: 100
    ServerListRefreshInterval: 1000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
    zoneAffinity.minAvailableServers: 2