oneserver:
  advertiseIp: 0.0.0.0
  port: 10080

server:
  port: -1
management:
  port: 9001
  security:
    enabled: false

cool-app:
  ribbon:
    listOfServers: 127.0.0.1:10080
    NFLoadBalancerPingInterval: 100
    ServerListRefreshInterval: 1000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 0
    OkToRetryOnAllOperations: false
    zoneAffinity.minAvailableServers: 2